#! /bin/bash

# export .env vars
export $(grep "DB_PASSWORD" .env)
export $(grep "DB_CONTAINER_NAME" .env)
export $(grep "DB_NAME" .env)

# local vars
today="`date +"%Y-%m-%d"`"
dump_path=data/mysql

# check arg1
if [[ $1 == "save" ]]; then

    # check if output file exists
    if [ -e $dump_path/$today.sql ]; then
        echo "Dump $dump_path/$today.sql already exists."
        exit
    fi

    # mysqldump
    docker exec $DB_CONTAINER_NAME bash -c "export MYSQL_PWD=$DB_PASSWORD && mysqldump $DB_NAME > $dump_path/$today.sql"

    echo "DB dumped to $dump_path/$today.sql"

elif [[ $1 == "load" ]]; then
    # get last dump file
    last_dump=$(ls $dump_path | sort -V | tail -n 1)

    # check if there is any dump
    if [[ $last_dump == "" ]]; then
        echo "No dump to load."
        exit
    fi

    # drop and recreate DB
    docker exec $DB_CONTAINER_NAME bash -c "export MYSQL_PWD=$DB_PASSWORD && mysqladmin --force drop $DB_NAME && mysqladmin create $DB_NAME"

    # upload DB
    docker exec $DB_CONTAINER_NAME bash -c "export MYSQL_PWD=$DB_PASSWORD && mysql $DB_NAME < /data/mysql/$last_dump"

    echo "$last_dump Loaded in DB."
else
    echo "Usage: db [save|load]"
    echo "Example: db save"
    echo "Example: db load"
fi